services:
    auth.provider.db_email:
        class: marttiphpbb\webpush\auth\email
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }

    auth.provider.db_username_or_email:
        class: marttiphpbb\webpush\auth\username_or_email
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }

    marttiphpbb.webpush.listener:
        class: marttiphpbb\webpush\event\listener
        arguments:
            - '@user'
            - '@template'
            - '@language'
            - '@config'
        tags:
            - { name: event.listener }

    marttiphpbb.webpush.console.info:
        class: marttiphpbb\webpush\console\info
        arguments:   
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: console.command }

    marttiphpbb.webpush.service.store:
        class: marttiphpbb\webpush\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.webpush.notification.method.webpush:
        class: marttiphpbb\webpush\method\webpush
        shared: false
        arguments:
            - '@user_loader'
            - '@user'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: notification.method }
