services:
    auth.provider.db_email:
        class: marttiphpbb\webpushnotifications\auth\email
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }

    auth.provider.db_username_or_email:
        class: marttiphpbb\webpushnotifications\auth\username_or_email
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }

    marttiphpbb.webpushnotifications.listener:
        class: marttiphpbb\webpushnotifications\event\listener
        arguments:
            - '@user'
            - '@template'
            - '@language'
            - '@config'
        tags:
            - { name: event.listener }

    marttiphpbb.webpushnotifications.console.info:
        class: marttiphpbb\webpushnotifications\console\info
        arguments:   
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: console.command }

    marttiphpbb.webpushnotifications.service.store:
        class: marttiphpbb\webpushnotifications\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'           